title: Solution 8 Project Toolkit
description: Activities, workshops, tools, and materials for complex system design and design thinking projects.
theme: just-the-docs

url: https://le-dawg.github.io

aux_links:
  GitHub Repository: https://github.com/le-dawg/S8-Project-Toolkit
